// app/components/ui/Icons.tsx
import {
  FiHome,
  FiUsers,
  FiBook,
  FiCheckSquare,
  FiUser,
  FiLogOut,
  FiMenu,
  FiChevronDown,
  FiChevronUp,
  FiPlus,
  FiTrash2,
  FiEdit,
  FiEye,
  FiClock,
  FiCheck,
  FiX,
  FiArrowRight,
  FiArrowLeft,
  FiBookOpen,
  FiBarChart2,
  FiTarget,
  FiCalendar,
  FiList,
  FiSettings,
  FiSearch,
  FiFilter,
  FiDownload,
  FiUpload,
  FiShare,
  FiMessageSquare,
  FiBell,
  FiStar,
  FiAward,
} from "react-icons/fi";

export {
  FiHome as HomeIcon,
  FiUsers as UsersIcon,
  FiBook as BookIcon,
  FiCheckSquare as TasksIcon,
  FiUser as UserIcon,
  FiLogOut as LogoutIcon,
  FiMenu as MenuIcon,
  FiChevronDown as ChevronDownIcon,
  FiChevronUp as ChevronUpIcon,
  FiPlus as PlusIcon,
  FiTrash2 as TrashIcon,
  FiEdit as EditIcon,
  FiEye as EyeIcon,
  FiClock as ClockIcon,
  FiCheck as CheckIcon,
  FiX as XIcon,
  FiArrowRight as ArrowRightIcon,
  FiArrowLeft as ArrowLeftIcon,
  FiBookOpen as BookOpenIcon,
  FiBarChart2 as ChartIcon,
  FiTarget as TargetIcon,
  FiCalendar as CalendarIcon,
  FiList as ListIcon,
  FiSettings as SettingsIcon,
  FiSearch as SearchIcon,
  FiFilter as FilterIcon,
  FiDownload as DownloadIcon,
  FiUpload as UploadIcon,
  FiShare as ShareIcon,
  FiMessageSquare as MessageIcon,
  FiBell as BellIcon,
  FiStar as StarIcon,
  FiAward as AwardIcon,
};
